syntax = "proto3";

message OrderStage {
  double timeStampFromMidnight = 1;
  string stageName = 2;
}

enum OrderStatus {
  NEW = 0;
  ACKED = 1;
  TRIGGER_PENDING = 2;
  APPROVED = 3;
  REJECTED = 4;
  FAILED = 5;
  EXECUTED = 6;
  DELIVERY_AWAITED = 7;
  CANCELLED = 8;
  CANCELLATION_REQUESTED = 9;
  MODIFICATION_REQUESTED = 10;
  COMPLETED = 11;
}

enum OrderDuration {
  IOC = 0;
  DAY = 1;
  GTD = 2;
  GTC = 3;
  EOS = 4;
}

enum Exchange {
  BSE = 0;
  NSE = 1;
  MCX = 2;
  MCXSX = 3;
  NCDEX = 4;
  US = 5;
}

enum Segment {
  CASH = 0;
  FNO = 1;
  CURRENCY = 2;
  COMMODITY = 3;
}

enum Product {
  CNC = 0;
  MIS = 1;
  CO = 2;
  BO = 3;
  NRML = 4;
  ARB = 5;
  MTF = 6;
}

enum OrderType {
  MKT = 0;
  LIMIT = 1;
  SL = 2;
  SL_M = 3;
}

enum TransactionType {
  BUY = 0;
  SELL = 1;
}

message OrderDetail {
  int32 quantity = 1;
  int64 price = 2;
  int64 triggerPrice = 3;
  int32 filledQuantity = 4;
  int32 remainingQuantity = 5;
  int64 averageFillPrice = 6;
  string orderId = 7;
  string exchangeOrderId = 8;
  OrderStatus orderStatus = 9;
  OrderDuration duration = 10;
  Exchange exchange = 11;
  Segment segment = 12;
  Product product = 13;
  OrderType orderType = 14;
  TransactionType transactionType = 15;
  string remark = 16;
  string contractId = 22;
  string guiOrderId = 23;
}

message OrderBroadcast {
  repeated OrderStage stages = 1;
  OrderDetail orderDetail = 2;
}
