/**
 * gb_scoring_v2/adapter/index.js — THE READ-ONLY ADAPTER.
 *
 * V3 spec Section 5: "READ-ONLY ADAPTER -> RAW RECORDER". Section 2: "Integration
 * is through a read-only adapter" and "No edits to existing backend files."
 *
 * This module READS GB's existing outputs and nothing else. It has no write path
 * to any backend file: the only writes in this subtree live in the recorder, and
 * they go to data/v2_sessions (the recorder's own directory). That split is the
 * isolation the spec asks for -- a bug here cannot corrupt the live engine.
 *
 * A note on the read source. The spec's ideal is an in-process tap on GB's scan.
 * We cannot have one without editing the backend, so the adapter reads the same
 * artifacts GB already publishes:
 *   data/live_signals.json    -- the old engine's scan output (rows + counts + pacing)
 *   data/live_tick_movers.json-- the live tick board
 *   data/live_calls.json      -- open calls, which are FORCED and never dropped
 * Both a file read and an HTTP read are supported; the file is the default because
 * it needs no server and cannot be blocked by a port change.
 */
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { toSnapshot } = require('./snapshot');
const { TAGS, FIELD_REGISTRY, tagOf, isKnown, flowProvenance } = require('./provenance');
// './config/index' explicitly, NOT './config' — the superseded draft gb_scoring_v2/config.js
// shadows the config/ directory for Node's resolver, and requiring it would silently load
// the wrong thresholds.
const { stableStringify } = require('../config/index');

const ROOT = path.join(__dirname, '..', '..');
const FILES = {
  signals: path.join(ROOT, 'data', 'live_signals.json'),
  ticks: path.join(ROOT, 'data', 'live_tick_movers.json'),
  calls: path.join(ROOT, 'data', 'live_calls.json'),
  // Cross-source enrichment for the STATIC facts the tick feed lacks. Both are
  // existing GB artifacts -- read, never written.
  quality: path.join(ROOT, 'data', 'universe_filtered.json'),   // close, atrPct, avgTurnoverCr, avgVol20, volBand
  shortlist: path.join(ROOT, 'data', 'universe_shortlist.json'), // + marketCap, spreadPct, delayedBy, activity
};

function readJson(file, fallback = null) {
  try { return JSON.parse(fs.readFileSync(file, 'utf8')); } catch (_) { return fallback; }
}

/**
 * loadGB({ source }) -> the raw GB payload. Never throws, never writes.
 * `stale` is surfaced rather than hidden: the spec's whole point is that a
 * snapshot must be honest about how old it is (Section 8 latency gate).
 */
function loadGB(opts = {}) {
  const receiptTs = Date.now();
  const p = readJson(FILES.signals, null);
  if (!p) return { ok: false, reason: 'data/live_signals.json unreadable', receiptTs, payload: null };
  const rows = p.signals || p.rows || [];
  return {
    ok: true,
    receiptTs,
    source: FILES.signals,
    generatedAt: p.generatedAt || null,
    ageMs: p.generatedAt ? receiptTs - Date.parse(p.generatedAt) : null,
    marketOpen: p.marketOpen,
    market: p.market || null,
    counts: p.counts || null,
    pacing: p.pacing || null,
    banned: p.banned || [],
    payload: p,
    rows,
  };
}

/** The post-close quality set, keyed by symbol. Read-only. */
function loadQuality() {
  const j = readJson(FILES.quality, null);
  const rows = (j && (j.stocks || j.results || [])) || [];
  const m = new Map();
  for (const r of rows) if (r && r.symbol) m.set(String(r.symbol).toUpperCase(), r);
  return m;
}

/** The funnel's screening shortlist, keyed by symbol. Absent until the funnel runs. */
function loadScreened() {
  const j = readJson(FILES.shortlist, null);
  const rows = (j && j.stocks) || [];
  const m = new Map();
  for (const r of rows) if (r && r.symbol) m.set(String(r.symbol).toUpperCase(), r);
  return m;
}

/**
 * CAPTURE THE AUX INPUTS — the reproducibility contract for any frozen baseline.
 *
 * The gates read static facts (avgVol20, marketCap, spreadPct, dayPct, atrPct) from two
 * files that GB RE-WRITES ON ITS OWN SCHEDULE: universe_shortlist.json is regenerated by
 * the 5-minute funnel cycle. A baseline that reads them live is not a baseline, because
 * the number it reports depends on when you ask.
 *
 * MEASURED, 2026-09-25 09:19 scan: dropping the enrichment entirely changes the gate
 * verdict of 53 of 289 rows either way. That is not a rounding error — it is the whole
 * difference between 230/59/0 and 229/60/0 on the same tape.
 *
 * So a freeze captures the rows it used, by content, and every later re-check re-reads
 * the PIN rather than whatever those files happen to say now.
 */
function captureAux() {
  const rowsOf = (j) => (j && (j.stocks || j.results || [])) || [];
  const q = readJson(FILES.quality, null);
  const s = readJson(FILES.shortlist, null);
  return {
    capturedAt: new Date().toISOString(),
    quality: { file: path.basename(FILES.quality), rows: rowsOf(q) },
    screened: { file: path.basename(FILES.shortlist), rows: rowsOf(s) },
  };
}

/** Rebuild the keyed lookups a snapshot needs from a captured (or live) aux bundle. */
function auxToMaps(aux) {
  const key = (rows) => {
    const m = new Map();
    for (const r of (rows || [])) if (r && r.symbol) m.set(String(r.symbol).toUpperCase(), r);
    return m;
  };
  return {
    quality: key(aux && aux.quality && aux.quality.rows),
    screened: key(aux && aux.screened && aux.screened.rows),
  };
}

/** A short content hash of one aux bundle, so two captures are comparable at a glance. */
function auxHash(aux) {
  if (!aux) return null;
  const pick = (a) => (a && a.rows ? a.rows : []).slice()
    .sort((x, y) => String(x.symbol).localeCompare(String(y.symbol)));
  return crypto.createHash('sha256')
    .update(stableStringify({ quality: pick(aux.quality), screened: pick(aux.screened) }))
    .digest('hex').slice(0, 12);
}

/**
 * One normalized snapshot per symbol per scan (Phase 2 done-when).
 * Each row is enriched from the quality set and the screening shortlist so the
 * gates have the static inputs the tick feed never carries.
 */
function snapshots(gb, opts = {}) {
  if (!gb || !gb.ok) return [];
  const quality = opts.quality || loadQuality();
  const screened = opts.screened || loadScreened();
  const base = { receiptTs: gb.receiptTs, generatedAt: gb.generatedAt, market: gb.market };
  return gb.rows.map(r => {
    const sym = String(r.symbol).toUpperCase();
    return toSnapshot(r, Object.assign({}, base, {
      quality: quality.get(sym) || null,
      screened: screened.get(sym) || null,
    }));
  }).filter(Boolean);
}

/** Open calls + watchlist, which stage A must never drop (spec Section 8 / funnel contract). */
function forcedSymbols() {
  const calls = readJson(FILES.calls, null);
  if (!calls) return [];
  const arr = Array.isArray(calls) ? calls : (calls.calls || []);
  const out = new Set();
  for (const c of arr) {
    if (!c || !c.symbol) continue;
    if (c.status === 'OPEN' || c.open === true || c.exitAt == null) out.add(String(c.symbol).toUpperCase());
  }
  return [...out];
}

/** A compact census of what the feed actually carries -- the Phase 1 evidence. */
function feedCensus(gb) {
  if (!gb || !gb.ok) return null;
  const rows = gb.rows || [];
  const fields = ['ltp', 's10', 's15', 's20', 's30', 'roc1', 'roc3', 'roc5', 'roc15', 'roc60', 'volX', 'volRoc', 'volume', 'dayValue', 'totBuy', 'totSell', 'flowBias', 'vwap', 'poc', 'vaHigh', 'vaLow', 'daily.atrPct', 'market', 'bid', 'ask', 'spread', 'rsi', 'adx'];
  const at = (r, k) => k.split('.').reduce((o, p) => (o == null ? undefined : o[p]), r);
  const census = {};
  for (const f of fields) {
    let present = 0, nonZero = 0;
    for (const r of rows) { const v = at(r, f); if (v !== undefined && v !== null) { present++; if (v !== 0) nonZero++; } }
    census[f] = { present, nonZero, of: rows.length };
  }
  return { rows: rows.length, depth: { deep: rows.filter(r => !r.tickOnly).length, tickOnly: rows.filter(r => r.tickOnly).length }, census };
}

/** Tag coverage across the whole payload: how much of what we record is inferred. */
function provenanceSummary(snaps) {
  const counts = { OBSERVED: 0, DERIVED: 0, INFERRED: 0, VERIFY: 0, UNKNOWN: 0 };
  for (const s of snaps) for (const k of Object.keys(s.provenance)) counts[s.provenance[k]]++;
  const inferredOnlyFlows = snaps.filter(s => s.flow.provenance && s.flow.provenance.inferredOnly).length;
  return { counts, inferredOnlyFlows, of: snaps.length, registry: Object.keys(FIELD_REGISTRY).length };
}

/**
 * directionOf(row) — the trade side a GB row RECORDS, in one place.
 *
 * Never inferred from the outcome and never from the sign of the momentum: a shadow
 * view or a baseline that fabricates a direction shows disagreements the engine never
 * had, and a gate audit then attributes them to the wrong gate.
 *
 * It lives here rather than in each consumer because the shadow board and the Phase-4
 * baseline both need it, and two copies of one rule is exactly how the gates' location
 * read drifted from the location engine's (see the 200x scale bug).
 *
 * A row with no side (normal for HOLD/TRACK before a setup forms) returns null, which
 * makes GATE_DIRECTION cap at WATCH rather than pass. That is the honest outcome.
 */
function directionOf(row) {
  if (!row) return null;
  const w = String(row.want || '').toUpperCase();
  if (w === 'LONG' || w === 'BUY') return 'LONG';
  if (w === 'SHORT' || w === 'SELL') return 'SHORT';
  const s = String(row.signal || '').toUpperCase();
  if (s === 'BUY') return 'LONG';
  if (s === 'SHORT') return 'SHORT';
  const d = row.dirSign;
  if (d === 1) return 'LONG';
  if (d === -1) return 'SHORT';
  return null;
}

module.exports = { FILES, loadGB, loadQuality, loadScreened, snapshots, captureAux, auxToMaps, auxHash, forcedSymbols, feedCensus, provenanceSummary, readJson, directionOf, TAGS, tagOf, isKnown, flowProvenance };
